import = [
  "~/.config/alacritty/base16-themes/colors/base16-default-dark-256.toml",
]

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[env]
TERM = "xterm-256color"

[font]
size = 22
offset = {}

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[[keyboard.bindings]]
chars = "\u001bF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
key = "Q"
mods = "Control"
action = "Quit"

[window]
decorations = "Full"
dynamic_title = false
startup_mode = "Maximized"

[window.dimensions]
columns = 130
lines = 40
